[versions]
# Mappings
parchment = "2024.11.17"
parchmentMinecraft = "1.21.1"
# Plugins
modDevGradle = "2.0.80"
kotlin = "2.1.20"
# Dependencies
minecraft = "1.21.1"
neoforge = "21.1.159"
kotlinForForge = "5.7.0"
jei = "19.21.1.248"
top = "1.21_neo-12.0.3-5"

[libraries]
kotlinForForge = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kotlinForForge" }
jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
top = { group = "mcjty.theoneprobe", name = "theoneprobe", version.ref = "top" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
jei-api = ["jei-common-api", "jei-neoforge-api"]
